//! ADR-033 P0 — pure-Rust ports of llama.cpp's ggml-quants.c kernels.
//!
//! Each submodule is a byte-identity port of `quantize_row_<T>_ref` and
//! (where it diverges from `_ref`) `quantize_row_<T>_impl` from
//! `/opt/llama.cpp/ggml/src/ggml-quants.c` at the SHA recorded in
//! `data/llama_cpp_pin.txt`.
//!
//! Acceptance gate: each kernel's `#[test]`s load the byte-identity
//! fixtures at `tests/fixtures/ggml_quants/<type>_<n>_<variant>_{input,expected}.bin`
//! (generated by `scripts/ggml_quants_harness/gen` via the public
//! `ggml_quantize_chunk`) and assert `quantize(...) == expected`
//! byte-for-byte.
//!
//! v1 set (11 files): q2_k, q3_k, q4_0, q4_1, q5_0, q5_1, q4_k, q5_k,
//! q6_k, q8_0, iq4_nl. Per ADR-033 §P0 amendment A.

pub mod iq4_nl;
pub mod q4_0;
pub mod q4_1;
pub mod q5_0;
pub mod q5_1;
pub mod q8_0;
